### ISSUE TITLE
Support working-directory parameters

### ISSUE THREAD

**Issue by sezaru** [josecfreittas/elixir-coverage-feedback-action#5]
My repo has multiple elixir projects, normally I add this to my job:

```yaml
    defaults:
      run:
        working-directory: ./marketplace
```

Or directly adding the `working-directory` to the `run` itself.

I can't use your action in  my projects because of that.

**Comment by josecfreittas** [comment]
Hi, @sezaru. Added support to it in [v0.4](https://github.com/josecfreittas/elixir-coverage-feedback-action/releases/tag/v0.4).

Adding `working-directory` directly to the step or using the `defaults: run` don't work for custom actions, so the solution I found is to receive it as an input parameter, like this:

```yaml
      - name: Tests & Coverage
        uses: josecfreittas/elixir-coverage-feedback-action@v0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_threshold: 80
          working_directory: ./marketplace
```
